# Generated by Django 4.0.4 on 2022-05-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_conservationalist',
            field=models.BooleanField(default=False, verbose_name='Conservationalist'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_hunter',
            field=models.BooleanField(default=False, verbose_name='Hunter'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_landowner',
            field=models.BooleanField(default=False, verbose_name='landowner'),
        ),
    ]
