# Generated by Django 4.0.4 on 2022-05-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pig_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_id',
        ),
    ]
