# Generated by Django 4.0.4 on 2022-05-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pig_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=123123, max_length=300),
            preserve_default=False,
        ),
    ]
